# fly.toml app configuration file generated for ctpbot-v2 on 2023-07-17T15:52:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ctpbot-v2"
primary_region = "ams"

[mounts]
source="terraria_data"
destination="/files"